version: '3'

services:
  sulu_nginx:
    image: nginx:latest
    container_name: sulu_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/app/public
      - .docker/nginx/config/app.conf:/etc/nginx/conf.d/default.conf
    links:
      - sulu_php

  sulu_php:
    build: .docker/php-fpm
    container_name: sulu_php
    volumes:
      - .:/var/www/app
    links:
      - sulu_database

  sulu_database:
    image: mysql:5.7
    container_name: sulu_database
    command: mysqld --sql_mode=""
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sulu
      MYSQL_USER: sulu
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_sulu_data:/var/lib/mysql
  sulu_elasticsearch:
    image: elasticsearch:7.9.3
    ports:
      - "9200:9200"
    volumes:
      - data_elastic:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'

volumes:
  db_sulu_data:
  data_elastic:

